
INSERT INTO product 
(image, name, price_cents, stars, rating_count, type, size_chart_link, instructions_link, warranty_link) 
VALUES
('images/products/backpack.jpg', 'Waterproof Black Backpack', 1090, 4, 60, 'general', '', '', ''),
('images/products/umbrella.jpg', 'Windproof Travel Compact - Dark Green Umbrella', 1590, 4.5, 183, 'general', '', '', ''),
('images/products/athletic-cotton-socks-6-pairs.jpg', 'Black and Gray Athletic Cotton Socks - 6 Pairs', 1090, 4.5, 87, 'general', '', '', ''),
('images/products/intermediate-composite-basketball.jpg', 'Intermediate Size Basketball', 2095, 4, 127, 'general', '', '', ''),
('images/products/adults-plain-cotton-tshirt-2-pack-teal.jpg', 'Adults Plain Cotton T-Shirt - 2 Pack', 799, 4.5, 56, 'clothing', 'images/clothing-size-chart.png', '', ''),
('images/products/black-2-slot-toaster.jpg', '2 Slot Toaster - Black', 1899, 5, 2197, 'appliance', '', 'images/appliance-instructions.png', 'images/appliance-warranty.png'),
('images/products/6-piece-white-dinner-plate-set.jpg', '6 Piece White Dinner Plate Set', 2067, 4, 37, 'general', '', '', ''),
('images/products/6-piece-non-stick-baking-set.webp', '6-Piece Nonstick, Carbon Steel Oven Bakeware Baking Set', 3499, 4.5, 175, 'general', '', '', ''),
('images/products/plain-hooded-fleece-sweatshirt-yellow.jpg', 'Plain Hooded Fleece Sweatshirt', 2400, 4.5, 317, 'general', '', '', ''),
('images/products/luxury-tower-set-6-piece.jpg', 'Luxury Towel Set - Graphite Gray', 3599, 4.5, 144, 'general', '', '', ''),
('images/products/liquid-laundry-detergent-plain.jpg', 'Liquid Laundry Detergent, 110 Loads, 82.5 Fl Oz', 2899, 4.5, 305, 'general', '', '', ''),
('images/products/knit-athletic-sneakers-gray.jpg', 'Waterproof Knit Athletic Sneakers - Gray', 3390, 4, 89, 'general', '', '', ''),
('images/products/women-chiffon-beachwear-coverup-black.jpg', 'Women''s Chiffon Beachwear Cover Up - Black', 2070, 4.5, 235, 'clothing', 'images/clothing-size-chart.png', '', ''),
('images/products/round-sunglasses-black.jpg', 'Round Sunglasses', 1560, 4.5, 30, 'general', '', '', ''),
('images/products/women-beach-sandals.jpg', 'Women''s Two Strap Buckle Sandals - Tan', 2499, 4.5, 562, 'general', '', '', ''),
('images/products/blackout-curtain-set-beige.webp', 'Blackout Curtains Set 4-Pack - Beige', 4599, 4.5, 232, 'general', '', '', ''),
('images/products/men-slim-fit-summer-shorts-gray.jpg', 'Men''s Slim-Fit Summer Shorts', 1699, 4, 160, 'general', '', '', ''),
('images/products/electric-glass-and-steel-hot-water-kettle.webp', 'Electric Glass and Steel Hot Tea Water Kettle - 1.7-Liter', 3074, 5, 846, 'appliance', '', 'images/appliance-instructions.png', 'images/appliance-warranty.png'),
('images/products/facial-tissue-2-ply-18-boxes.jpg', 'Ultra Soft Tissue 2-Ply - 18 Box', 2374, 4, 99, 'general', '', '', ''),
('images/products/straw-sunhat.webp', 'Straw Lifeguard Sun Hat', 2200, 4, 215, 'general', '', '', ''),
('images/products/sky-flower-stud-earrings.webp', 'Sterling Silver Sky Flower Stud Earrings', 1799, 4.5, 52, 'general', '', '', ''),
('images/products/women-stretch-popover-hoodie-black.jpg', 'Women''s Stretch Popover Hoodie', 1374, 4.5, 2465, 'clothing', 'images/clothing-size-chart.png', '', ''),
('images/products/bathroom-rug.jpg', 'Bathroom Bath Rug Mat 20 x 31 Inch - Grey', 1250, 4.5, 119, 'general', '', '', ''),
('images/products/women-knit-ballet-flat-black.jpg', 'Women''s Knit Ballet Flat', 2640, 4, 326, 'general', '', '', ''),
('images/products/men-golf-polo-t-shirt-blue.jpg', 'Men''s Regular-Fit Quick-Dry Golf Polo Shirt', 1599, 4.5, 2556, 'clothing', 'images/clothing-size-chart.png', '', ''),
('images/products/trash-can-with-foot-pedal-50-liter.jpg', 'Trash Can with Foot Pedal - Brushed Stainless Steel', 8300, 4.5, 2286, 'general', '', '', ''),
('images/products/duvet-cover-set-blue-twin.jpg', 'Duvet Cover Set with Zipper Closure', 2399, 4, 456, 'general', '', '', ''),
('images/products/women-chunky-beanie-gray.webp', 'Women''s Chunky Cable Beanie - Gray', 1250, 5, 83, 'general', '', '', ''),
('images/products/men-chino-pants-beige.jpg', 'Men''s Classic-fit Pleated Chino Pants', 2290, 4.5, 9017, 'general', '', '', ''),
('images/products/men-athletic-shoes-green.jpg', 'Men''s Athletic Sneaker', 3890, 4, 229, 'general', '', '', ''),
('images/products/men-navigator-sunglasses-brown.jpg', 'Men''s Navigator Sunglasses Pilot', 1690, 3.5, 42, 'general', '', '', ''),
('images/products/non-stick-cooking-set-15-pieces.webp', 'Non-Stick Cookware Set, Pots, Pans and Utensils - 15 Pieces', 6797, 4.5, 511, 'general', '', '', ''),
('images/products/vanity-mirror-silver.jpg', 'Vanity Mirror with Heavy Base - Chrome', 1649, 4.5, 130, 'general', '', '', ''),
('images/products/women-french-terry-fleece-jogger-camo.jpg', 'Women''s Fleece Jogger Sweatpant', 2400, 4.5, 248, 'general', '', '', ''),
('images/products/double-elongated-twist-french-wire-earrings.webp', 'Double Oval Twist French Wire Earrings - Gold', 2400, 4.5, 117, 'general', '', '', ''),
('images/products/round-airtight-food-storage-containers.jpg', 'Round Airtight Food Storage Containers - 5 Piece', 2899, 4, 126, 'general', '', '', ''),
('images/products/coffeemaker-with-glass-carafe-black.jpg', 'Coffeemaker with Glass Carafe and Reusable Filter - 25 Oz, Black', 2250, 4.5, 1211, 'appliance', '', 'images/appliance-instructions.png', 'images/appliance-warranty.png'),
('images/products/blackout-curtains-black.jpg', 'Blackout Curtains Set 42 x 84-Inch - Black, 2 Panels', 3099, 4.5, 363, 'general', '', '', ''),
('images/products/cotton-bath-towels-teal.webp', '100% Cotton Bath Towels - 2 Pack, Light Teal', 2110, 4.5, 93, 'general', '', '', ''),
('images/products/knit-athletic-sneakers-pink.webp', 'Waterproof Knit Athletic Sneakers - Pink', 3390, 4, 89, 'general', '', '', ''),
('images/products/countertop-blender-64-oz.jpg', 'Countertop Blender - 64oz, 1400 Watts', 10747, 4, 3, 'appliance', '', 'images/appliance-instructions.png', 'images/appliance-warranty.png'),
('images/products/floral-mixing-bowl-set.jpg', '10-Piece Mixing Bowl Set with Lids - Floral', 3899, 5, 679, 'general', '', '', ''),
('images/products/kitchen-paper-towels-30-pack.jpg', '2-Ply Kitchen Paper Towels - 30 Pack', 5799, 4.5, 1045, 'general', '', '', ''),
('images/products/men-cozy-fleece-zip-up-hoodie-red.jpg', 'Men''s Full-Zip Hooded Fleece Sweatshirt', 2400, 4.5, 3157, 'general', '', '', '');
